apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/argoproj/argocd
  newTag: v2.10.7

resources:
- https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.10.7
- cmp-plugin.yaml

patches:
- path: argocd-repo-server.yaml
